// <auto-generated />
namespace DrWhoDatabase.Migration.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FB100LinkingTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FB100LinkingTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201307081849013_FB100-LinkingTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
