// <auto-generated />
namespace DrWhoDatabase.Migration.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FB101EpisodeTracking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FB101EpisodeTracking));
        
        string IMigrationMetadata.Id
        {
            get { return "201307100131055_FB101-EpisodeTracking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
